name: docker
on:
  workflow_dispatch: {}
  release:
    types:
      - published

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  docker:
    name: build-publish
    uses: leukosaima/gh-actions/.github/workflows/docker-github-builder.yaml@4a9a55a45da6215127bd44b1129215ea7085ca69 # main
    secrets: inherit
